<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is: EntExt
 * The Initial Developer of the Original Code is EntExt.
 * All Rights Reserved.
 * If you have any questions or comments, please email: devel@entext.com
 ************************************************************************************/
$languageStrings = array(
    'LBL_IMPORT_MODULE'            => 'Импорт из Vtiger'               ,
    'LBL_VTIGER_EXTENSION_STORE'   => 'Расширения Vtiger'      , 
    'LBL_PUBLISHER'                => 'Издатель'            ,
    'LBL_LICENSE'                  => 'Лицензия'            ,
    'LBL_PUBLISHED_ON'             => 'Дата издания'     ,
    'LBL_INSTALL'                  => 'Установить'        ,
    'LBL_UPGRADE'                  => 'Обновить'            ,
    'LBL_VERSION'                  => 'Версия'                , // KEY 5.x: VTLIB_LBL_PACKAGE_VERSION
    'LBL_DECLINE'                  => 'Decline'                     , 
    'LBL_ACCEPT_AND_INSTALL'       => 'Подтверждение и установка'          , 
    'LBL_ALREADY_EXISTS'           => 'Уже существует' ,
    'LBL_OK'                       => 'OK'                          , 
    'LBL_EXTENSION_NOT_COMPATABLE' => 'Расширение не совместимо с Vtiger', 
    'LBL_INVALID_FILE'             => 'Неправильный файл'                , 
    'LBL_NO_LICENSE_PROVIDED'      => 'Нет лицензии'         , 
    'LBL_INSTALLATION'             => 'Установка'                , 
    'LBL_FAILED'                   => 'Ошибка'                ,
    'LBL_SUCCESSFULL'              => 'Успешно'                 , 
    'LBL_INSTALLATION_LOG'         => 'Лог установки'            , 

    //Extension Store translations
    'LBL_SEARCH_FOR_EXTENSION'  => 'Поиск расширений ...',
    'LBL_DOWNLOADS' => 'Загрузки',
    'LBL_NO_EXTENSIONS_FOUND' => 'Расширения не найдены',
    'LBL_REGISTER_USER' => 'Регистрация пользователя',
    'LBL_SETUP_CARD_DETAILS' => 'Setup Card Details',
    'LBL_SETUP_CARD' => 'Детали карты',
    'LBL_CARD_NUMBER' => 'Номер карты',
    'LBL_EXP_MONTH' => 'Месяц',
    'LBL_EXP_YEAR' => 'Год',
    'LBL_CVC_CODE' => 'CVC код',
    'LBL_RESET' => 'Сброс',
    'LBL_EXTENSION_STORE' => 'Магазин расширений',
    'LBL_INSTALLED' => 'Установлен',
    'LBL_UPDATE_CARD_DETAILS' => 'Обновление деталей карты',
    'LBL_BY' => 'По',
    'LBL_RATINGS' => 'Оценки',
    'LBL_DESCRIPTION' => 'Описание',
    'LBL_AUTHOR_INFORMATION' => 'Информация об авторе',
    'LBL_AUTHOR_NAME' => 'Имя',
    'LBL_PHONE' => 'Телефон',
    'LBL_EMAIL' => 'E-mail',
    'LBL_SCREEN_SHOTS' => 'Скриншоты',
    'LBL_CUSTOMER_RATINGS' => 'Оценки пользователей',
    'LBL_CUSTOMER_REVIEWS' => 'Отзывы пользователей',
    'LBL_WRITE_A_REVIEW' => 'Написать отзыв',
    'LBL_CUSTOMER_REVIEW' => 'Обзор пользователя',
    'LBL_REVIEW' => 'Обзор',
    'LBL_CUSTOMERS_REVIEWED' => 'Отзывы пользователей',
    'LBL_SINGLE_CUSTOMER_REVIEWED' => 'Один из отзывов клиентов',
    'LBL_INSTALLATION_FAILED' => 'Ошибка установки',
    'LBL_SUCCESSFULL_INSTALLATION' => 'Успешная установка',
    'Install' => 'Установить',
    'Upgrade' => 'Обновить',
    'LBL_RATE_IT' => 'Оценить',

    'LBL_SEARCH_FOR_AN_EXTENSION'  => 'Поиск расширений ...',
    'LBL_REGISTER_TO_MARKET_PLACE' => 'Регистрация в Marketplace',
    'LBL_MARKETPLACE_REGISTRATION' => 'Регистрация в Marketplace',
    'LBL_CREATE_AN_ACCOUNT' => 'Создать новый аккаунт',
    'LBL_INSTALL_FROM_ZIP' => 'становка из zip-архива',
    'LBL_MORE_DETAILS' => 'Подробнее',
    'LBL_UNINSTALL' => 'Удалить',
    'LBL_LAUNCH' => 'Launch',
    'LBL_SIGN_UP_FOR_FREE' => 'Бесплатная регистрация',
    'LBL_EMAIL_ADDRESS' => 'E-mail',
    'LBL_FIRST_NAME' => 'Имя',
    'LBL_LAST_NAME' => 'Фамилия',
    'LBL_COMPANY_NAME' => 'Компания',
    'LBL_PASSWORD' => 'Пароль',
    'LBL_CONFIRM_PASSWORD' => 'Подтверждение пароля',
    'LBL_REGISTER' => 'Регистрация',
    'LBL_EXTENSION_STORE_LOGIN' => 'Extensionstore Login',
    'LBL_REMEMBER_ME' => 'Запомнить меня',
    'LBL_TRY_IT' => 'Try it',
    'LBL_TRIAL_INSTALLED' => 'Trial Installed',
    'LBL_BUY' => 'Купить ',
    'LBL_LOGIN_TO_MARKET_PLACE' => 'Войти в Marketplace',
    'LBL_LOGIN' => 'Войти',
    'LBL_PHP_EXTENSION_LOADER_IS_NOT_AVAIABLE' => 'Please install extension loader',
    'LBL_INSTALL_EXTENSION_LOADER' => 'Install Extension Loader',
    'LBL_TO_CONTINUE_USING_EXTENSION_STORE' => 'To continue using Extension Store please install ',
    'LBL_DOWNLOAD' => 'Download',
    'LBL_COMPATIABLE_EXTENSION' => ' and enable it as zend_extension.',
    'LBL_MORE_DETAILS_ON_INSTALLATION' => 'For more details on installation ',
    'LBL_READ_HERE' => 'read here',
    'LBL_REVIEWS' => 'отзывов',


    

    'LBL_VERIFY_IMPORT_DETAILS'    => 'Подтвердить детали импорта',
    'I would like to update now.'  => 'Обновить сейчас',
    'LBL_MODULE_NAME' => 'Имя модуля',
    'LBL_REQ_VTIGER_VERSION' => 'Версия Vtiger',
    'LBL_LICENSE_ACCEPT_AGREEMENT' => 'Я принимаю лицензионные условия.',
    'LBL_EXISTS'=>'Существует',
    'LBL_PROCEED_WITH_IMPORT' => 'Вы хотите продолжить импорт?',
    'LBL_VERSION_NOT_SUPPORTED' => 'Версия модуля не совместима с данной версией Vtiger',
    'LBL_FINISH' => 'Завершено',
    'LBL_IMPORT_ZIP' => 'Импорт из файла',
    'LBL_NOT_FOUND' => "Извините, на данной момент нет ни одного расширения для вашей версии CRM",
    'LBL_INVALID_IMPORT_TRY_AGAIN' => ' предусмотрено для импорта модуля! Попробуйте еще раз.',
    'LBL_IMPORTED_MODULE' => ' был импортирован успешно.',
    'LBL__IMPORTING_MODULE' => 'Импорт модуля',

    'LBL_UPDATE_MODULE_FROM_FILE' => 'Обновить модуль из файла',
    'LBL_UPDATED_MODULE' => ' был обновлен успешно.',
    'LBL__UPDATING_MODULE' => 'Обновление модуля',
    'LBL_IMPORT_MODULE_FROM_FILE' => 'Импорт модуля из файла',

    'LBL_IMPORT_MODULE_FROM_ZIP' => 'Установка из zip-архива',
    'LBL_DISCLAIMER_FOR_IMPORT_FROM_ZIP' => '<b>Отказ от ответственности</b> <br> Модуль, который вы собираетесь установить не был проверен Vtiger. Пользовательские модули могут содержать проблемы безопасности, а также перезаписать системные файлы и поставить под риск функционирование CRM. Устанавливайте данный модуль только если вы доверяете издателю!',
    'LBL_ACCEPT_WITH_THE_DISCLAIMER' => 'Я принимаю отказ и хотел бы продолжить',
    'LBL_IMPORT_NOW' => 'Импорт',
    'LBL_UPDATE_NOW' => 'Обновить',
);
$jsLanguageStrings = array(
    'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_THIS_EXTENSION'  => 'Пожалуйста, подробнее Уст.Карту установить это расширение',
    'JS_UPDATE_CARD_DETAILS' => 'Обновление карты Подробности',
    'JS_ON' => 'вкл',
    'JS_RATINGS' => 'Оценки',



    'JS_PLEASE_INSTALL_EXTENSION_LOADER_TO_INSTALL_THIS_EXTENSION_FROM_BELOW_LINK' => 'Пожалуйста установите загрузчик расширений для установки по ссылке ниже',
    'JS_EXTENSION_STORE_IS_NOT_SUPPOTED_WOULD_YOU_LIKE_TO_INSTALL' => 'Расширение не поддерживается, хотите установить?',
    'JS_PHP_EXTENSION_LOADER_NOT_INSTALLED' => 'PHP загрузчик расширений не установлен ',
    'JS_CLICK_HERE' => 'Нажмите здесь ',
    'JS_FOR_INSTALLATION' => 'для установки',
    'JS_IMPORT_SUCCESSFULL' => 'Импорт прошел успешно',
    'JS_IMPORTED_MODULE' => 'Модуль успешно импортирован.',
    'JS_UPDATE_SUCCESSFULL' => 'Обновление успешно',
    'JS_UPDATED_MODULE' => 'Модуль успешно обновлен',
);