<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is: EntExt
 * The Initial Developer of the Original Code is EntExt.
 * All Rights Reserved.
 * If you have any questions or comments, please email: devel@entext.com
 ************************************************************************************/
$languageStrings = array(
	'SINGLE_Calendar'              => 'Календарь',
	'LBL_ADD_TASK'                 => 'Добавить Задачу',
	'LBL_ADD_EVENT'                => 'Добавить Событие', 
	'LBL_RECORDS_LIST'             => 'Список',
	'LBL_EVENTS'                   => 'События',
	'LBL_TODOS'                    => 'Задачи',
	'LBL_CALENDAR_SETTINGS'        => 'Настройки Календаря',
	'LBL_CALENDAR_SHARING'         => 'Использовать совмесно с', 
	'LBL_DEFAULT_EVENT_DURATION'   => 'Продолжительность события по умолчанию',
	'LBL_CALL'                     => 'звонить по телефону', 
	'LBL_OTHER_EVENTS'             => 'Другие События',
	'LBL_MINUTES'                  => 'минут',
	'LBL_SELECT_USERS'             => 'Выбор Пользователей',
	'LBL_EVENT_OR_TASK'			   => 'Событие / Задача',
	'LBL_TASK_INFORMATION'         => 'Информация о Задаче',
	'Subject'                      => 'Тема',
	'Start Date & Time'            => 'Дата и время начала',
	'Activity Type'                => 'Тип действия',
	'Send Notification'            => 'Отправить уведомление',
	'Location'                     => 'Место проведения',
	'End Date & Time'              => 'Дата и время завершения',
	'LBL_ACTIVITY_TYPES'           => 'Типы',
	'LBL_CONTACTS_SUPPORT_END_DATE' => 'Дата завершения поддержки',
	'LBL_CONTACTS_BIRTH_DAY'       => 'Дата рождения',
	'LBL_ADDED_CALENDARS'          => 'Календари',
	'Call'                         => 'Звонок',
	'Meeting'                      => 'Встреча',
	'Task'                         => 'Задачf',
	'Planned'                      => 'Запланировано',
    'Held'                         => 'Проведено',
    'Not Held'                     => 'Не проведено',
	'Completed'                    => 'Завершено',
	'Pending Input'                => 'В ожидании',
	'Not Started'                  => 'Не начато',
	'Deferred'                     => 'Отсрочено',
	'Medium'                       => 'Средний',
	'LBL_CHANGE_OWNER'             => 'Изменить Ответственного', 
	'LBL_EVENT'                    => 'Событие',
	'LBL_TASK'                     => 'Задача',
	'LBL_TASKS'                    => 'Задачи' ,
	'LBL_CALENDAR_VIEW'            => 'Мой Календарь',
	'LBL_SHARED_CALENDAR'          => 'Общий Календарь',
	'LBL_DAY0'                     => 'Воскресенье',
	'LBL_DAY1'                     => 'Понедельник',
	'LBL_DAY2'                     => 'Вторник',
	'LBL_DAY3'                     => 'Среда',
	'LBL_DAY4'                     => 'Четверг',
	'LBL_DAY5'                     => 'Пятница',
	'LBL_DAY6'                     => 'Суббота',
	'first'                        => 'Первый',
	'last'                         => 'Последний',
	'LBL_DAY_OF_THE_MONTH'         => 'день месяца',
	'LBL_ON'                       => 'в',
	'Daily'                        => 'Ежедневно',
	'Weekly'                       => 'Еженедельно',
	'Monthly'                      => 'Ежемесячно',
	'Yearly'                       => 'Ежегодно',
    'LBL_DEFAULT_STATUS_TYPE'      => 'Статус и тип по умолчанию',
    'LBL_STATUS'                   => 'Статус',
    'LBL_TYPE'                     => 'Тип',

	//Fixing colors for Shared Calendar and My Calendar
	'LBL_EDIT_COLOR'               => 'Редактировать цвет',
	'LBL_ADD_CALENDAR_VIEW'        => 'Добавить тип',
	'LBL_SELECT_USER_CALENDAR'     => 'Выберите User календарь',
	'LBL_SELECT_CALENDAR_COLOR'    => 'Выберите цвет',
	'LBL_EDITING_CALENDAR_VIEW'    => 'Редактирование типа',
	'LBL_DELETE_CALENDAR'          => 'Удалить тип',
	'LBL_SELECT_ACTIVITY_TYPE'     => 'Выберите тип',
	'Tasks'                        => 'Задачи',


    'Due Date'                     => 'Дата выполнения',
    'Mobile Call'                  => 'Звонок с мобильного',
    'Reminder Interval'            => 'Интервал напоминания',
    'Starting Day of the week'     => 'Неделя начинается с',
    'Default Activity View'        => 'Вид календаря по умолчанию',
    'Date Format'                  => 'Формат даты',
    'Calendar Hour Format'         => 'Часовой формат',
    'Day starts at'                => 'Начало дня в календаре',
    'Time Zone'                    => 'Часовой пояс',
    '1 Minute'                     => '1 минута',
    '5 Minutes'                    => '5 минут',
    '15 Minutes'                   => '15 минут',
    '30 Minutes'                   => '30 минут',
    '45 Minutes'                   => '45 минут',
    '1 Hour'                       => '1 час',
    '1 Day'                        => '1 день',
    'Thursday'                     => 'Четверг',
    'Due Date & Time'              => 'Дата и время выполнения',
    'LBL_IMPORT_RECORDS'           => 'Импортируемые записи',
    'ICAL_FORMAT'                  => 'iCal формат',
    'End Date'                     => 'Дата завершения',
    'LBL_FIELD_MAPPING'            => 'Соответствие полей',
    'Description'                  => 'Описание',
    'Recurrence'                   => 'Повторить',
    'Send Reminder'                => 'Отправить уведомление',
    'Time Start'                   => 'Время начала',
    'End Time'                     => 'Время окончания',
    'Visibility'                   => 'Видимость',
    'Duration'                     => 'Продолжительность',
    'Duration Minutes'             => 'Продолжительность минут',
    'No Time'                      => 'Нет времени',
    'LBL_HIDE_COMPLETED_EVENTS'    => 'Не показывать завершенные события',
    'LBL_RESULT'                   => 'Результат',
    'LBL_TOTAL_EVENTS_IMPORTED'    => 'Всего событий импортировано',
    'LBL_TOTAL_EVENTS_SKIPPED'     => 'Всего событий пропущено',
    'LBL_TOTAL_TASKS_IMPORTED'     => 'Всего задач импортировано',
    'LBL_TOTAL_TASKS_SKIPPED'      => 'Всего задач пропущено',
    'LBL_FINISH'                   => 'Финиш',
    'LBL_UNDO_LAST_IMPORT'         => 'Отменить последний импорт',
    'LBL_LAST_IMPORT_UNDONE'       => 'Импорт отменен',
);
$jsLanguageStrings = array(
	'LBL_ADD_EVENT_TASK'           => '+ Событие/Задачу',
	'JS_TASK_IS_SUCCESSFULLY_ADDED_TO_YOUR_CALENDAR' => 'Задача успешно добавлена в календарь',
	'LBL_CANT_SELECT_CONTACT_FROM_LEADS' => 'Невозможно выбрать связанные Контакты для Обращений',
    'JS_FUTURE_EVENT_CANNOT_BE_HELD' => 'Не может нести за будущее',
	
	//Calendar view label translation
    'LBL_MONTH' => 'Месяц',
    'LBL_TODAY' => 'Сегодня',
    'LBL_DAY' => 'День',
    'LBL_WEEK' => 'Неделя',

    'LBL_SUNDAY' => 'Воскресенье',
    'LBL_MONDAY' => 'Понедельник',
    'LBL_TUESDAY' => 'Вторник',
    'LBL_WEDNESDAY' => 'Среда',
    'LBL_THURSDAY' => 'Четверг',
    'LBL_FRIDAY' => 'Пятница',
    'LBL_SATURDAY' => 'Суббота',

    'LBL_SUN' => 'Вс',
    'LBL_MON' => 'Пн',
    'LBL_TUE' => 'Вт',
    'LBL_WED' => 'Ср',
    'LBL_THU' => 'Чт',
    'LBL_FRI' => 'Пт',
    'LBL_SAT' => 'Сб',

    'LBL_JANUARY' => 'Январь',
    'LBL_FEBRUARY' => 'Февраль',
    'LBL_MARCH' => 'Март',
    'LBL_APRIL' => 'Апрель',
    'LBL_MAY' => 'Май',
    'LBL_JUNE' => 'Июнь',
    'LBL_JULY' => 'Июль',
    'LBL_AUGUST' => 'Август',
    'LBL_SEPTEMBER' => 'Сентябрь',
    'LBL_OCTOBER' => 'Октябрь',
    'LBL_NOVEMBER' => 'Ноябрь',
    'LBL_DECEMBER' => 'Декабрь',

    'LBL_JAN' => 'Янв',
    'LBL_FEB' => 'Фев',
    'LBL_MAR' => 'Мар',
    'LBL_APR' => 'Апр',
    'LBL_MAY' => 'Май',
    'LBL_JUN' => 'Июн',
    'LBL_JUL' => 'Июл',
    'LBL_AUG' => 'Авг',
    'LBL_SEP' => 'Сен',
    'LBL_OCT' => 'Окт',
    'LBL_NOV' => 'Ноя',
    'LBL_DEC' => 'Дек',
	
	'LBL_ALL_DAY' => 'Дни',
	
	'Mobile Call' => 'Звонок по мобильному телефону',
	//End
	
	//Fixing colors for Shared Calendar and My Calendar
    'JS_CALENDAR_VIEW_COLOR_UPDATED_SUCCESSFULLY' => 'Цвет типа успешно обновлен',
    'JS_CALENDAR_VIEW_DELETE_CONFIRMATION' => 'Вы уверены, что хотите удалить этот тип?',
    'JS_CALENDAR_VIEW_ADDED_SUCCESSFULLY' => 'Тип успешно добавлен',
    'JS_CALENDAR_VIEW_DELETED_SUCCESSFULLY' => 'Тип успешно удален',
    'JS_NO_CALENDAR_VIEWS_TO_ADD' => 'Больше нет типов для добавления',
    'JS_EDIT_CALENDAR' => 'Редактировать календарь',


    'LBL_SYNC_BUTTON'              => 'Синхронизировать',
    'LBL_SYNCRONIZING'             => 'Синхронизация....',
    'LBL_NOT_SYNCRONIZED'          => 'Не синхронизировано',
    'LBL_FIELD_MAPPING'            => 'Соответствие полей',
    'JS_RECORD_DELETED'            => 'Запись удалена',
    'JS_NO_DELETE_PERMISSION'      => 'У Вас недостаточно прав для удаления элементов Календаря',
    'JS_NO_EDIT_PERMISSION'        => 'У Вас недостаточно прав для изменения элементов Календаря',
);
