<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is: EntExt
 * The Initial Developer of the Original Code is EntExt.
 * All Rights Reserved.
 * If you have any questions or comments, please email: devel@entext.com
 ************************************************************************************/
$languageStrings = array(
	'Events'                       => 'События'              , 
	'SINGLE_Events'                => 'Событие'              , 
	'LBL_ADD_RECORD'               => 'Добавить Событие'                   ,
	'LBL_RECORDS_LIST'             => 'Список'                   ,
	'LBL_EVENTS'                   => 'События',
	'LBL_TODOS'                    => 'Календарь',
	'LBL_HOLD_FOLLOWUP_ON'         => 'Последующее напоминание в'      ,
    'LBL_CREATE_FOLLOWUP_EVENT'    => 'Создание следить за событие' ,
	'LBL_EVENT_INFORMATION'        => 'Детали События'               ,
	'LBL_RECURRENCE_INFORMATION'   => 'Повторить'          ,
	'LBL_RELATED_TO'               => 'Связан с'             , 
	'Start Date & Time'            => 'Дата и время начала',
	'Recurrence'                   => 'Повторить'                      ,
	'Send Notification'            => 'Отправить уведомление'           ,
	'Location'                     => 'Место проведения'                    ,
	'Send Reminder'                => 'Отправить напоминание'               ,
	'End Date & Time'              => 'Дата и время завершения',
	'Activity Type'                => 'Тип действия'     ,
	'Visibility'                   => 'Видимость'                  ,
	'Private'                      => 'Личное',
	'Public'                       => 'Публичное',
	'Call'                         => 'Звонок'                , 
	'Meeting'                      => 'Встреча'              , 
	'Planned'                      => 'Запланировано'  , 
	'Held'                         => 'Проведено',
	'Not Held'                     => 'Не проведено' ,
	'LBL_DAYS'                     => 'дней'                        ,
	'LBL_HOURS'                    => 'часов'                       ,
	'LBL_DAYS_TYPE'                => 'День'                      ,
	'LBL_WEEKS_TYPE'               => 'Неделя'                     ,
	'LBL_MONTHS_TYPE'              => 'Месяц'                    ,
	'LBL_YEAR_TYPE'                => 'Год'                        ,
	'LBL_FIRST'                    => 'Первая'                , 
	'LBL_LAST'                     => 'Последняя'          , 
	'LBL_SM_SUN'                   => 'Вс'                         ,
	'LBL_SM_MON'                   => 'Пн'                         ,
	'LBL_SM_TUE'                   => 'Вт'                         ,
	'LBL_SM_WED'                   => 'Ср'                         ,
	'LBL_SM_THU'                   => 'Чт'                         ,
	'LBL_SM_FRI'                   => 'Пт'                         ,
	'LBL_SM_SAT'                   => 'Сб'                         ,
	'LBL_DAY0'                     => 'Воскресенье'                      ,
	'LBL_DAY1'                     => 'Понедельник'                      ,
	'LBL_DAY2'                     => 'Вторник'                     , 
	'LBL_DAY3'                     => 'Среда'                   , 
	'LBL_DAY4'                     => 'Четверг'                    , 
	'LBL_DAY5'                     => 'Пятница'                      , 
	'LBL_DAY6'                     => 'Суббота'                    , 
	'Daily'                        => 'Ежедневно'                      ,
	'Weekly'                       => 'Еженедельно'                     ,
	'Monthly'                      => 'Ежемесячно'                    ,
	'Yearly'                       => 'Ежегодно'                        ,
	'LBL_REPEATEVENT'              => 'Повторить один раз в каждые'        ,
	'LBL_UNTIL'                    => 'До'                       , 
	'LBL_DAY_OF_THE_MONTH'         => 'день месяца'            , 
	'LBL_ON'                       => ' '                          ,
	'LBL_CALENDAR_VIEW'            => 'Представление календаря'               ,
	'LBL_INVITE_USER_BLOCK'        => 'Пригласить'                      ,
	'LBL_INVITE_USERS'             => 'Пользователи'                ,


    'Medium'                       => 'Средний',
    'Mobile Call'                  => 'Звонок с мобильного',
    'Busy'                         => 'Занят',
);