<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is: EntExt
 * The Initial Developer of the Original Code is EntExt.
 * All Rights Reserved.
 * If you have any questions or comments, please email: devel@entext.com
 ************************************************************************************/
$languageStrings = array(
    'Products'                     => 'Товары'                ,
    'SINGLE_Products'              => 'Товар'                  ,
    'LBL_ADD_RECORD'               => 'Добавить Товар',
    'LBL_RECORDS_LIST'             => 'Список Товаров',
    'LBL_PRODUCT_INFORMATION'      => 'Описание Товара',
    'LBL_IMAGE_INFORMATION'        => 'Изображение'     ,
    'LBL_STOCK_INFORMATION'        => 'Информация склада',
    'LBL_MORE_CURRENCIES'          => 'Больше валют'     ,
    'LBL_PRICES'                   => 'Цены Товаров',
    'LBL_PRICE'                    => 'Цена'                    ,
    'LBL_RESET_PRICE'              => 'Сбросить цену'   ,
    'LBL_RESET'                    => 'Сбросить'            ,
    'LBL_ADD_TO_PRICEBOOKS'        => 'Добавить в Каталоги',
    'Product No'                   => 'Товар №'              ,
    'Part Number'                  => 'Код товара'         ,
    'Product Active'               => 'Активен'              ,
    'Manufacturer'                 => 'Производитель'  ,
    'Product Category'             => 'Категория Товара',
    'Website'                      => 'Веб-сайт'             ,
    'Mfr PartNo'                   => 'Код производителя',
    'Vendor PartNo'                => 'Код Поставщика' ,
    'Usage Unit'                   => 'Единица измерения',
    'Handler'                      => 'Ответственный за склад',
    'Reorder Level'                => 'Пороговый остаток для дозаказа',
    'Tax Class'                    => 'Класс налога'     ,
    'Serial No'                    => 'Серийный номер' ,
    'Qty In Stock'                 => 'Кол-во на складе',
    'Product Sheet'                => 'Характеристики',
    'Qty In Demand'                => 'Минимальный заказ',
    'GL Account'                   => 'Счёт в гл.книге' ,
    'Product Image'                => 'Изображение'      ,
    'Unit Price'                   => 'Цена за единицу',
    'Commission Rate'              => 'Комиссия (%)'        ,
    'Qty/Unit'                     => 'Кол-во/Ед.'           ,
    '--None--'                     => '--Нет--'                  ,
    'Hardware'                     => 'Оборудование'    ,
    'Software'                     => 'ПО'                        ,
    'CRM Applications'             => 'CRM-Приложения'    ,
    '300-Sales-Software'           => '300-Продажи-ПО'     ,
    '301-Sales-Hardware'           => '301-Продажи-Оборудование',
    '302-Rental-Income'            => '302-Рента-Доход'   ,
    '303-Interest-Income'          => '303-Комиссионные-Доход',
    '304-Sales-Software-Support'   => '304-Продажи-ПО-Поддержка',
    '305-Sales Other'              => '305-Продажи-Другое',
    '306-Internet Sales'           => '306-Интернет-Продажи',
    '307-Service-Hardware Labor'   => '307-Услуги-Настройка Оборудования',
    '308-Sales-Books'              => '308-Продажи-Периферия',
    'Box'                          => 'Ящик'                    ,
    'Carton'                       => 'Коробка'              ,
    'Caton'                        => 'Катушка'              ,
    'Dozen'                        => 'Дюжина'                ,
    'Each'                         => 'шт.'                       ,
    'Hours'                        => 'Часов'                  ,
    'Impressions'                  => 'Показ'                  ,
    'Lb'                           => 'кг'                        ,
    'M'                            => 'M'                           ,
    'Pack'                         => 'Пакет'                  ,
    'Pages'                        => 'Страница'            ,
    'Pieces'                       => 'Единица'              ,
    'Reams'                        => 'Стопка'                ,
    'Sheet'                        => 'Лист'                    ,
    'Spiral Binder'                => 'Переплет'            ,
    'Sq Ft'                        => 'м2'                         ,
    'LBL_PRODUCTSMOD_DISABLED'     => 'Модуль Продукты выключен',


    'LBL_CONVERSION_RATE'          => 'Обменный курс'   ,
    'Unit Code'                    => 'Код единицы измерения',
    'Manuf. Country'               => 'Страна происхождения',
    'Customs ID'                   => 'Номер ГТД',
    'Mf. Country Code'             => 'Код страны',
    'Days'                         => 'Дни',
    'Incidents'                    => 'События',
);