<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is: EntExt
 * The Initial Developer of the Original Code is EntExt.
 * All Rights Reserved.
 * If you have any questions or comments, please email: devel@entext.com
 ************************************************************************************/
$languageStrings = array(
    'Reports'                      => 'Отчеты'                ,
    'SINGLE_Reports'               => 'Отчет'                  ,
    'LBL_FOLDER_NOT_EMPTY'         => 'Папка не пуста'         ,
    'LBL_MOVE_REPORT'              => 'Переместить Отчеты',
    'LBL_CUSTOMIZE'                => 'Изменить',
    'LBL_REPORT_EXPORT_EXCEL'      => 'Экспорт в Excel',
    'LBL_REPORT_PRINT'             => 'Печать',
    'LBL_STEP_1'                   => 'Шаг 1',
    'LBL_STEP_2'                   => 'Шаг 2',
    'LBL_STEP_3'                   => 'Шаг 3',
    'LBL_REPORT_DETAILS'           => 'Детали Отчета'   ,
    'LBL_SELECT_COLUMNS'           => 'Выберите колонки',
    'LBL_FILTERS'                  => 'Фильтры'              ,
    'LBL_FOLDERS'                  => 'Папки',
    'LBL_ADD_NEW_FOLDER'           => 'Добавить новую Папку',
    'LBL_FOLDER_NAME'              => 'Имя Папки',
    'LBL_FOLDER_DESCRIPTION'       => 'Описание Папки',
    'LBL_WRITE_YOUR_DESCRIPTION_HERE' => 'Введите Описание',
    'LBL_DUPLICATES_EXIST'         => 'Отчет уже существует',
    'LBL_FOLDERS_LIST'             => 'Список Папок',
    'LBL_DENIED_REPORTS'           => 'Отклоненные Отчеты',
    'LBL_NO_OF_RECORDS'            => 'Количество записей',
    'LBL_ADD_RECORD'               => 'Добавить Отчет',
    'LBL_ADD_FOLDER'               => 'Добавить Папку',
    'LBL_REPORT_DELETE_DENIED'     => 'Не хватает прав для удаления Отчета',
    'LBL_FOLDER_CAN_NOT_BE_DELETED' => 'Папка не может быть удалена',
    'LBL_REPORTS_LIST'             => 'Список Отчетов',
    'LBL_REPORT_NAME'              => 'Название Отчета',
    'LBL_REPORT_FOLDER'            => 'Папка для отчётов',
    'LBL_DESCRIPTION'              => 'Описание'            ,
    'PRIMARY_MODULE'               => 'Основной модуль',
    'LBL_SELECT_RELATED_MODULES'   => 'Выберите связанный модуль',
    'LBL_MAX'                      => 'макс',
    'LBL_NEXT'                     => 'Далее',
    'LBL_REPORTS'                  => 'Список Отчетов',
    'LBL_GROUP_BY'                 => 'Сгруппировать',
    'LBL_SORT_ORDER'               => 'Отсортировать',
    'LBL_ASCENDING'                => 'По возрастанию',
    'LBL_DESCENDING'               => 'По убыванию',
    'LBL_CALCULATIONS'             => 'Расчеты'            ,
    'LBL_COLUMNS'                  => 'Колонки'              ,
    'LBL_SUM_VALUE'                => 'Сумма',
    'LBL_AVERAGE'                  => 'Среднее',
    'LBL_LOWEST_VALUE'             => 'Наименьшая величина',
    'LBL_HIGHEST_VALUE'            => 'Наибольная величина',
    'LBL_GENERATE_REPORT'          => 'Сгенерировать Отчет',
    'LBL_SUM'                      => 'СУМ',
    'LBL_AVG'                      => 'СРЕДН',
    'LBL_MIN'                      => 'МИН',
    'LBL_FIELD_NAMES'              => 'Названия Полей',
    'LBL_REPORT_CSV'               => 'Экспорт в CSV',
    'LBL_VIEW_DETAILS'             => 'Просмотр',
    'LBL_GENERATE_NOW'             => 'Сформировать'    ,
    'Report Name'                  => 'Название Отчета',
    'Account and Contact Reports'  => 'Отчеты по Контактам и Контрагентам',
    'Lead Reports'                 => 'Отчеты по Обращениям',
    'Potential Reports'            => 'Отчеты по Сделкам',
    'Activity Reports'             => 'Отчеты по Деятельности',
    'HelpDesk Reports'             => 'Отчеты по Заявкам в Поддержку',
    'Product Reports'              => 'Отчеты по Товарам',
    'Quote Reports'                => 'Отчеты по Предложениям',
    'PurchaseOrder Reports'        => 'Отчеты по Закупкам',
    'SalesOrder Reports'           => 'Отчеты по Заказам',
    'Invoice Reports'              => 'Отчеты по Счетам',
    'Campaign Reports'             => 'Отчеты по Кампаниям',
    'Contacts by Accounts'         => 'Контакты по Контрагентам',
    'Contacts without Accounts'    => 'Контакты без Контрагентов',
    'Contacts by Potentials'       => 'Контакты по Сделкам',
    'Contacts related to Accounts' => 'Контакты, относящиеся к Контрагентам',
    'Contacts not related to Accounts' => 'Контакты, не относящиеся к Контрагентам',
    'Contacts related to Potentials' => 'Контакты относящиеся к Сделкам',
    'Lead by Source'               => 'Обращения по Источникам',
    'Lead Status Report'           => 'Отчет по Статусу Обращения',
    'Potential Pipeline'           => 'Конвейер Сделок',
    'Closed Potentials'            => 'Закрытые Сделки',
    'Potential that have Won'      => 'Сделки с Выигрышем',
    'Tickets by Products'          => 'Заявки по Товарам',
    'Tickets by Priority'          => 'Заявки по Приоритетам',
    'Open Tickets'                 => 'Открытые Заявки',
    'Tickets related to Products'  => 'Заявки, относящиеся к Товарам',
    'Tickets that are Open'        => 'Открытые Заявки',
    'Product Details'              => 'Информация о Товаре',
    'Products by Contacts'         => 'Товары по Контактам',
    'Product Detailed Report'      => 'Детальный отчет по Товарам',
    'Products related to Contacts' => 'Товары относящиеся к Контактам',
    'Open Quotes'                  => 'Открытые Предложения',
    'Quotes Detailed Report'       => 'Детальный Отчет Запросов',
    'Quotes that are Open'         => 'Открытые Запросы',
    'PurchaseOrder by Contacts'    => 'Закупки по Контактам',
    'PurchaseOrder Detailed Report' => 'Детальный отчет по Закупкам',
    'PurchaseOrder related to Contacts' => 'Закупки, относящиеся к Контактам',
    'Invoice Detailed Report'      => 'Детальный Отчет по Счетам',
    'Last Month Activities'        => 'Деятельность за прошлый месяц',
    'This Month Activities'        => 'Деятельность за этот месяц',
    'Campaign Expectations and Actuals' => 'Ожидания и Факты по Кампаниям',
	'SalesOrder Detailed Report'   => 'Детальный Отчет по Заказам',
    'Email Reports'                => 'E-mail отчеты',
    'Contacts Email Report'        => 'Отчет по письмам Контактов',
    'Accounts Email Report'        => 'Отчет по письмам Контрагентов',
    'Leads Email Report'           => 'Отчет по письмам Обращений',
    'Vendors Email Report'         => 'Отчет по письмам Поставщиков',
    'Emails sent to Contacts'      => 'Письма, отправленные Контактам',
    'Emails sent to Organizations' => 'Письма, отправленные Контрагентам',
    'Emails sent to Leads'         => 'Письма, отправленные Обращениям',
    'Emails sent to Vendors'       => 'Письма, отправленные поставщикам',
    'LBL_PRINT_REPORT'             => 'Напечатать Отчет',
    'LBL_RECORDS'                  => 'Записи'                ,
    'LBL_LIMIT_EXCEEDED'           => 'Отображается только 1000+ записей. Используйте CSV или Excel экспорт чтобы просмотреть все записи',
    'LBL_TOP'                      => 'Топ'                  ,
	'LBL_ALL_REPORTS'              => 'Все отчеты'                 ,
	'LBL_CALCULATION_CONVERSION_MESSAGE' => 'Расчеты основаны на выбранной в CRM валюте',

    'LBL_CREATING_REPORT' => 'Создание Отчета',
    'LBL_EDITING_REPORT' => 'Редактирование Отчета',
    'LBL_SCHEDULE_REPORTS' => 'Отчет по расписанию',
    'LBL_DAILY'            => 'Ежедневно',
    'LBL_WEEKLY'           => 'Еженедельно',
    'LBL_SPECIFIC_DATE'    => 'В определенный день',
    'LBL_MONTHLY_BY_DATE'  => 'Каждый месяц по определенным дням',
    'LBL_YEARLY'           => 'Ежегодно',
    'LBL_CHOOSE_DATE' 			=> 'Выберите дату',
    'LBL_ON_THESE_DAYS' 		=> 'Дни',
    'LBL_SELECT_MONTH_AND_DAY' 	=> 'Выберите месяц и день',
    'LBL_SELECTED_DATES' 		=> 'Выбранные даты',
    'LBL_EXCEEDING_MAXIMUM_LIMIT' => 'Максимальный лимит превышен',
    'LBL_RUN_REPORT' 			=> 'Сформировать',
    'LBL_SELECT_RECIEPIENTS' 	=> 'Получатели',
    'LBL_SPECIFIC_EMAIL_ADDRESS' => 'Отправить уведомление на почту',



    'LBL_AT_TIME'          => 'Время начала',

    //charts labels
    'LBL_SELECT_CHART_TYPE' => 'Выберите тип диаграммы',
    'LBL_CLICK_THROUGH_NOT_AVAILABLE' => 'Недоступно если Вы выбрали больше одного модуля',
    'LBL_TOTAL_SUM_OF' => 'Сумма %s',
    'LBL_AVG_OF' => 'Среднее %s',
    'LBL_MIN_OF' => 'Минимум %s',
    'LBL_MAX_OF' => 'Максимум %s',
    'LBL_RECORD_COUNT' => 'Количество записей',
    'LBL_PIE_CHART' => 'Круговая диаграмма',
    'LBL_VERTICAL_BAR_CHART' => 'Вертикальная гистограмма',
    'LBL_HORIZONTAL_BAR_CHART' => 'Горизонтальная гистограмма',
    'LBL_LINE_CHART' => 'Линейный график',
    'LBL_SELECT_CHART' => 'Выберите диаграмму',
    'LBL_CREATING_CHART_REPORT' => 'Создание диаграммы',
    'LBL_EDITING_CHART_REPORT' => 'Редактирование диаграммы',
    'LBL_GENERATE_CHART' => 'Создать',
    'LBL_SELECT_GROUP_BY_FIELD' => 'Выберите поле',
    'LBL_SELECT_DATA_FIELD' => 'Выберите данные',
    'LBL_MODIFY_CONDITION' => 'Изменить условия',
    'LBL_PLEASE_SELECT_ATLEAST_ONE_GROUP_FIELD_AND_DATA_FIELD' => 'Пожалуйста, выберите хотя бы одно поле и одни данные.',
    'LBL_FOR_BAR_GRAPH_AND_LINE_GRAPH_SELECT_3_MAX_DATA_FIELDS' => 'Для гистограмм и линейного графика Вы можете выбрать максимум 3 поля данных.',
    'LBL_DETAIL_REPORT' => 'Детальный отчет',
    'LBL_CHARTS' => 'Диаграммы',

    'LBL_AUTO_GENERATED_REPORT_EMAIL' => 'Это автосгенерированное письмо, отправленное из запланированного отчета.',

    'Pay date' => 'Дата',
    'Assigned To' => 'Ответственный',
    'Payer' => 'Контрагент',

    'LBL_MORE_RECORDS_TXT' => 'Показаны только 1000 записей. Для просмотра всех записей необходим экспорт.',
    'LBL_NEXT_TRIGGER_TIME' => 'Следующее время отправки/выполнения',
    'Templates' => 'Шаблоны',
    'Report templates for modules' => 'Шаблоны отчетов для модулей',
);
$jsLanguageStrings = array(
    'JS_DUPLICATE_RECORD'          => 'Дубликат отчета',
    'JS_CALCULATION_LINE_ITEM_FIELDS_SELECTION_LIMITATION' => 'Ограничение: Поля товарной части(Розничная цена, Скидка и Кол-во) могут использоваться только когда другие расчетные поля не выбраны.', // TODO: Review
    'JS_NO_CHART_DATA_AVAILABLE' => 'Нет данных',
);